<?
$aMenuLinks = Array(
    Array(
        "About us", 
        "/about-us/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Brands", 
        "/brands/",  
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Investors", 
        "/investors/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Partners", 
        "/partnership/", 
        Array(), 
        Array(), 
        "" 
    ),
);
?>